/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type ExecuteMsg = {
  join_swap_extern: {
    pool_id: number;
    share_out_min_amount: string;
    token_in: Coin;
    [k: string]: unknown;
  };
} | {
  exit_swap_share: {
    pool_id: number;
    share_in_amount: string;
    token_out_denom: string;
    token_out_min_amount: string;
    [k: string]: unknown;
  };
};
export type Uint128 = string;
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}