[package]
name = "strategy"
version = "1.0.0"
authors = []
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
prost = "0.11"
prost-types = "0.11"
bech32 = "0.9.0"
cw-utils = "1.0.1"
cw20 = { version = "1.1.0" } 
cosmwasm-std = { version = "1.0.0"}
schemars = "0.8.10"
serde = { version = "1.0.144", default-features = false, features = ["derive"] }
protobuf = { version = "3.2.0", features = ["with-bytes"] }
thiserror = { version = "1.0.23" }
